package cn.bw.studentserver.dao;

import cn.bw.studentserver.pojo.UserInfo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userinfo
     *
     * @mbggenerated
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userinfo
     *
     * @mbggenerated
     */
    int insertSelective(UserInfo record);

    List<UserInfo> getUserInfo();

    UserInfo getAUserInfo(String uname);

    UserInfo login(String uname,String upwd);
}